### ISSUE TITLE
Break long sentences on multiple lines

### ISSUE THREAD

**Issue by LeonardoGentile** [patorjk/figlet.js#15]
This is more a css related issue but specifically for this project.
I insert the resulting computed ascii in a `pre` tag and the problem comes when I have long sentences that I'd like to break on multiple lines.
I've tried with this css as suggested [here](http://stackoverflow.com/a/248013/1191416)

<pre>
pre {
  white-space: -moz-pre-wrap /* Mozilla, supported since 1999 */
  white-space: -pre-wrap /* Opera */
  white-space: -o-pre-wrap /* Opera */
  white-space: pre-wrap /* CSS3 - Text module (Candidate Recommendation) http://www.w3.org/TR/css3-text/#white-space */
  word-wrap: break-word /* IE 5.5+ */
}
</pre>

but this breaks the formatting. I have to revert to `pre { white-space: pre}` or things won't work.

I was wondering if anyone has already encountered (and possibly solved) this issue.

**Comment by patorjk** [comment]
Sorry for the delayed response. This is an interesting question. There are actually two types of space characters, non-breaking and breaking (which would wordwrap). So one way to fix this would be to use non-breaking space characters for all spaces except for the spaces that appear in the " " figlet character. Then only those spaces would break rather than spaces that might be in the middle of a character. I'll have to think about this, but I'll see if I can come up with something.

**Comment by LeonardoGentile** [comment]
:+1:

**Comment by titpetric** [comment]
A "hacky" fix would be just to replace all spaces with `&nbsp;` for html output. You will not be able to break figlet fonts with white-space css, as those are meant for actual *ttf* fonts. Figlet output for example, is meant to be a monospaced font, and is actually multiple lines for any letter/word it outputs - the word-wrap properties work on these lines.

**Comment by LeonardoGentile** [comment]
@patorjk have you had time to manage this? 
I know it's a very old question : ]

**Comment by patorjk** [comment]
Last night I thought about it, but wasn't sure how possible it was. The quick solution is to replace the space character with a non-breaking space character, example:

    var figlet = require('figlet');

    figlet('Hello World!!', function(err, data) {
        if (err) {
            console.log('Something went wrong...');
            console.dir(err);
            return;
        }
        console.log( data.replace(/ /g, ' ') ); // I copied the non-breaking space character from here: https://en.wikipedia.org/wiki/Non-breaking_space
    });

But this presents the same problem as using "white-space:pre". The formatting won't adjust for different page sizes. I think what you're asking is that when you have FIGlet text like this: 



```
<pre id="example1">
  __  .__    .__         .__                    __                   __   
_/  |_|  |__ |__| ______ |__| ______ _____    _/  |_  ____   _______/  |_ 
\   __\  |  \|  |/  ___/ |  |/  ___/ \__  \   \   __\/ __ \ /  ___/\   __\
 |  | |   Y  \  |\___ \  |  |\___ \   / __ \_  |  | \  ___/ \___ \  |  |  
 |__| |___|  /__/____  > |__/____  > (____  /  |__|  \___  >____  > |__|  
           \/        \/          \/       \/             \/     \/        
</pre>
```

You'd want the words to wrap as the page width changed. So if the page was smaller, the text might look like this:


```
<pre id="example2">
  __  .__    .__         .__                  
_/  |_|  |__ |__| ______ |__| ______ _____    
\   __\  |  \|  |/  ___/ |  |/  ___/ \__  \   
 |  | |   Y  \  |\___ \  |  |\___ \   / __ \_ 
 |__| |___|  /__/____  > |__/____  > (____  / 
           \/        \/          \/       \/  
  __                   __                     
_/  |_  ____   _______/  |_                   
\   __\/ __ \ /  ___/\   __\                  
 |  | \  ___/ \___ \  |  |                    
 |__|  \___  >____  > |__|                    
           \/     \/                          
</pre>
```

This kind of word wrapping can't automatically be done because the two outputs are completely different strings. 

However, you could achieve the desired effect if you generated multiple output strings and then used CSS Media Queries to display a particular string based on the page size. Example:

```
@media only screen and (max-width: 600px) {
    #example1 {
        display: none;
    }
    #example2 {
        display: block;
    }
}

@media only screen and (min-width: 601px) and (max-width:20000px) {
    #example1 {
        display: block;
    }
    #example2 {
        display: none;
    }
}
```

You can see this example in action here: https://codepen.io/patorjk/pen/GYmgoe

Once the browser is resized to be under 600px, the word will wrap.

Anyway, if there's a better way I'm open to other ideas, but as of right now I think the only way to get this effect is to manually setup several different versions of the text and then have CSS Media Queries display the desired version based on the page size.

**Comment by LeonardoGentile** [comment]
Thanks 👍 it's been a while since I've used your project, I'll take a look
