### ISSUE TITLE
Font file for Calvin is missing...?

### ISSUE THREAD

**Issue by osher** [patorjk/figlet.js#17]
I'm using figlet to draw a success banner in a prepublish hook,
I've been using it happily for quite a while, where the success banner choses a font in random - but I have encountered today the following error:

```
ERROR <proj>-compiler - processing ended { [Error: ENOENT, open '/opt/jenkins/jobs/<project>/workspace/node_modules/<utility-package>node_modules/figlet/lib/../fonts/Calvin.flf']
  errno: 34,
  code: 'ENOENT',
  path: '/opt/jenkins/jobs/<project>/workspace/node_modules/<utility-pkg>/node_modules/figlet/lib/../fonts/Calvin.flf' }
Error: ENOENT, open '/opt/jenkins/jobs/<project>/workspace/node_modules/<utility-pkg>/node_modules/figlet/lib/../fonts/Calvin.flf'
FATAL osg-rules-compiler:CLI - compilation complete with errors
npm ERR! weird error 1
npm ERR! not ok code 0

```
I could note that the font file for `Calvin` is missing on the disk...
I can see there `Calvin S` though...

maybe something is lost with names?

**Comment by osher** [comment]
Oi. My bad.
The list of fonts to random from got an error.
One of us decided that not all of the fonts look good, made a list and the error is there...

**Comment by patorjk** [comment]
I double checked and it looks like Calvin S was one of the fonts I converted over from TheDraw. I only converted over a hand full of fonts - do you think Calvin should be added? It's been a while since I looked. I only did a hand full because my process for converting over required some manual work.

Essentially I have a script that decodes TheDraw files (puts it into unicode and strips out the color information) as best as it can and then I paste the output into this editor - http://patorjk.com/figlet-editor/#/edit

A script that fully converts the files would be better, but I wasn't able to fully figure out the file format, so some manual work is needed to make sure all of the characters are correct.
